"""adding the name column in user table

Revision ID: 251fb43d879f
Revises: 81468698ace7
Create Date: 2026-04-26 10:48:24.096857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251fb43d879f'
down_revision = '81468698ace7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
