"""initial tables

Revision ID: 81468698ace7
Revises: 
Create Date: 2026-04-26 10:33:15.946031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81468698ace7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('muscle_group', sa.String(length=100), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_name'), ['name'], unique=True)

    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=True),
    sa.Column('protein_per_100g', sa.Float(), nullable=True),
    sa.Column('carbs_per_100g', sa.Float(), nullable=True),
    sa.Column('fat_per_100g', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('goal', sa.String(length=200), nullable=True),
    sa.Column('activity_level', sa.String(length=100), nullable=True),
    sa.Column('injury_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_log_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_log_user_id'), ['user_id'], unique=False)

    op.create_table('llm_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('llm_comments', sa.Text(), nullable=False),
    sa.Column('training_plan', sa.Text(), nullable=False),
    sa.Column('nutrition_plan', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_recommendation_user_id'), ['user_id'], unique=False)

    op.create_table('nutrition_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=True),
    sa.Column('quantity_g', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_log_food_id'), ['food_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nutrition_log_user_id'), ['user_id'], unique=False)

    op.create_table('user_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('text_chunk', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_embedding_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_embedding_user_id'))

    op.drop_table('user_embedding')
    with op.batch_alter_table('nutrition_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_nutrition_log_food_id'))

    op.drop_table('nutrition_log')
    with op.batch_alter_table('llm_recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_recommendation_user_id'))

    op.drop_table('llm_recommendation')
    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_log_exercise_id'))

    op.drop_table('exercise_log')
    op.drop_table('user')
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_name'))

    op.drop_table('food')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_name'))

    op.drop_table('exercise')
    # ### end Alembic commands ###
