"""Add user_saved column  to LLMRecommendation, this will be a flag column that user has reviewed the plan, made neccessary updates, then flag as user saved plan

Revision ID: 9ddc0bcbc1ca
Revises: 6d07969695ad
Create Date: 2026-05-09 10:09:20.947624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddc0bcbc1ca'
down_revision = '6d07969695ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_saved', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_recommendation', schema=None) as batch_op:
        batch_op.drop_column('user_saved')

    # ### end Alembic commands ###
