"""updated the llm table, that I need some help funtion to translate LLM output (json) to string to storage as text, then translate text back to diction for use in the app, basically structure conversion of the LLM recommendation 

Revision ID: 9f4a04e88064
Revises: 3dd894352f8e
Create Date: 2026-05-02 22:07:16.352136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4a04e88064'
down_revision = '3dd894352f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_plan_json', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('nutrition_plan_json', sa.Text(), nullable=False))
        batch_op.drop_column('training_plan')
        batch_op.drop_column('nutrition_plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrition_plan', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('training_plan', sa.TEXT(), nullable=False))
        batch_op.drop_column('nutrition_plan_json')
        batch_op.drop_column('training_plan_json')

    # ### end Alembic commands ###
